global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'middleware'
    metrics_path: '/api/internal/metrics'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'realtime'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:3002']
