apiVersion: 1

datasources:
  # PostgreSQL - Primary application database
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: vizora
    user: ${POSTGRES_USER:-postgres}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-postgres}
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: false
    editable: true

  # ClickHouse - Analytics database
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      defaultDatabase: default
      port: 8123
      server: clickhouse
      protocol: http
    isDefault: false
    editable: true

  # Prometheus - Metrics collection (if running)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      timeInterval: 15s
    isDefault: true
    editable: true
